Capa Dropout --- 0:00 min
===

* Última modificación: Marzo 7, 2022 | YouTube

* Adaptado de: https://keras.io/api/layers/regularization_layers/dropout/

Una capa Dropout fija aleatoriamente las unidades de entrada en cero con una frecuencia de `rate`en cada iteración del entrenamiento, lo cual ayuda a prevenir el sobre-ajuste. Las entradas que no son iguales a cero son escaladas por un factor de `1/(1-rate)` tal que la suma sobre todas las entradas no cambia.

La capa Dropout solo es aplicada durante el entrenamiento y no durante el pronostico (o inferencia).

Importación de librerías
---

In [1]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

tf.__version__

'2.8.0'

Ejemplos de uso
---

In [2]:
import numpy as np

tf.random.set_seed(0)
layer = tf.keras.layers.Dropout(
    rate=0.2,
    input_shape=(2,),
)
data = np.arange(10).reshape(5, 2).astype(np.float32)
data

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [3]:
layer(
    data,
    training=True,
)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.  ,  1.25],
       [ 2.5 ,  3.75],
       [ 5.  ,  6.25],
       [ 7.5 ,  8.75],
       [10.  ,  0.  ]], dtype=float32)>