Tutorial básico --- 0:00 min
===

* Última modificación: Marzo 1, 2022 | YouTube

Importación de librerías
---

In [1]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

Carga de datos
--

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

#
# Escalamiento del dataset
#
x_train, x_test = x_train / 255.0, x_test / 255.0

Especificación del modelo
--

In [3]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10),
    ]
)

Pronóstico con el modelo sin entrenar
--

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.44426614, -0.01677626,  0.01279202, -0.07599498,  0.34210083,
         0.32191107,  0.1690052 , -0.19370835,  0.7655732 ,  0.08679999]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.12455832, 0.07854971, 0.08090696, 0.07403315, 0.11246125,
        0.11021344, 0.09458634, 0.06581183, 0.17175707, 0.08712186]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.2053363

Entrenamiento del modelo
--

In [8]:
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2941 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1425 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1061 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0870 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0719 - accuracy: 0.9781


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0707 - accuracy: 0.9786 - 517ms/epoch - 2ms/step


[0.07068686187267303, 0.978600025177002]

In [11]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

Adición de una capa de entrenamiento
---

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.51076365e-09, 3.57254493e-09, 1.14346854e-04, 1.42001256e-04,
        2.50106576e-12, 1.47362780e-08, 6.39319665e-14, 9.99742329e-01,
        5.85599018e-08, 1.26317673e-06],
       [4.41358665e-08, 1.61150281e-04, 9.99733150e-01, 2.42262577e-05,
        1.66149890e-13, 7.40200194e-05, 3.77586457e-06, 5.05887953e-12,
        3.55560428e-06, 9.42879629e-12],
       [3.52352856e-07, 9.99664664e-01, 6.96827237e-06, 1.14383065e-05,
        5.24393290e-05, 1.87610738e-06, 1.16772526e-05, 2.00022638e-04,
        5.00875649e-05, 5.80169285e-07],
       [9.99966502e-01, 8.07580447e-10, 1.85401877e-05, 9.44201375e-08,
        3.28541319e-07, 9.22966478e-07, 2.74286595e-06, 1.15885234e-06,
        4.13973389e-09, 9.67436426e-06],
       [7.36573566e-06, 5.84294724e-10, 2.26177985e-06, 1.52925807e-07,
        9.98453021e-01, 1.15147645e-06, 1.09224047e-05, 2.75080558e-04,
        3.66662630e-06, 1.24632730e-03]], dtype=float32)>