# Capas personalizadas

* 30:00 min | Última modificación: Mayo 12, 2021 | [YouTube]

Adaptado de:

* https://www.tensorflow.org/tutorials/keras/keras_tuner

In [1]:
import tensorflow as tf
from tensorflow import keras

tf.__version__

'2.4.1'

## Operaciones con capas

In [2]:
#
# El número de entradas puede ser inferido directamente
# cuando se usa por primera vez la capa. La capa tiene
# 5 unidades de entrada y 10 unidades de salida.
#
# Recibe una matriz de None filas x 5 columnas
# 
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

#
# Aplica la capa a una matriz de 8x5. La salida es
# de 8x10
#
layer(tf.zeros([8, 5]))

<tf.Tensor: shape=(8, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

La lista completa de tipos de capas está disponible en https://www.tensorflow.org/api_docs/python/tf/keras/layers

In [3]:
#
# Variables presentes en la capa (pesos)
#
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.10145968,  0.15412611, -0.0714041 ,  0.02691042, -0.12088054,
          0.0187844 , -0.58307207, -0.39822525,  0.11007398,  0.16650784],
        [ 0.21515214, -0.4991439 , -0.33965996,  0.00812513, -0.01365894,
          0.14197701, -0.11235404, -0.18999389,  0.41039985, -0.35476902],
        [ 0.22937351, -0.18796757,  0.39723605,  0.612963  , -0.0100947 ,
         -0.4318191 ,  0.10401738, -0.13942915, -0.50483316, -0.31185895],
        [-0.6109286 , -0.23313871, -0.18126348,  0.45151287, -0.3541538 ,
         -0.46279556, -0.18286699,  0.19753182,  0.18867946,  0.25866342],
        [ 0.12898517,  0.10934025,  0.18978596, -0.592899  ,  0.11703497,
         -0.42217448, -0.60276365,  0.30424756,  0.43236953, -0.28672948]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [4]:
#
# Variables entrenables en la capa
#
layer.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.10145968,  0.15412611, -0.0714041 ,  0.02691042, -0.12088054,
          0.0187844 , -0.58307207, -0.39822525,  0.11007398,  0.16650784],
        [ 0.21515214, -0.4991439 , -0.33965996,  0.00812513, -0.01365894,
          0.14197701, -0.11235404, -0.18999389,  0.41039985, -0.35476902],
        [ 0.22937351, -0.18796757,  0.39723605,  0.612963  , -0.0100947 ,
         -0.4318191 ,  0.10401738, -0.13942915, -0.50483316, -0.31185895],
        [-0.6109286 , -0.23313871, -0.18126348,  0.45151287, -0.3541538 ,
         -0.46279556, -0.18286699,  0.19753182,  0.18867946,  0.25866342],
        [ 0.12898517,  0.10934025,  0.18978596, -0.592899  ,  0.11703497,
         -0.42217448, -0.60276365,  0.30424756,  0.43236953, -0.28672948]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [5]:
#
# Las variables tambien son accesibls a traves 
# de nombres personalizados
#
layer.kernel, layer.bias

(<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.10145968,  0.15412611, -0.0714041 ,  0.02691042, -0.12088054,
          0.0187844 , -0.58307207, -0.39822525,  0.11007398,  0.16650784],
        [ 0.21515214, -0.4991439 , -0.33965996,  0.00812513, -0.01365894,
          0.14197701, -0.11235404, -0.18999389,  0.41039985, -0.35476902],
        [ 0.22937351, -0.18796757,  0.39723605,  0.612963  , -0.0100947 ,
         -0.4318191 ,  0.10401738, -0.13942915, -0.50483316, -0.31185895],
        [-0.6109286 , -0.23313871, -0.18126348,  0.45151287, -0.3541538 ,
         -0.46279556, -0.18286699,  0.19753182,  0.18867946,  0.25866342],
        [ 0.12898517,  0.10934025,  0.18978596, -0.592899  ,  0.11703497,
         -0.42217448, -0.60276365,  0.30424756,  0.43236953, -0.28672948]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

## Creación de capas personalizadas

In [6]:
#
# Es obligatorio implementar el constructor
#  y las funciones build y call. La capa
# personalizada se deriva de Layer
#
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        #
        # Invoca al constructor de la clase base
        #
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        #
        # Construye el kernel. Note que se da el
        # tamaño de los tensores
        #
        self.kernel = self.add_weight(
            "kernel",
            shape=[int(input_shape[-1]), self.num_outputs],
            initializer="random_normal",
            trainable=True,
        )

    def call(self, inputs):
        #
        # Define las operaciones que hace la capa
        # y retorna el resultado
        #
        return tf.matmul(inputs, self.kernel)


#
# Crea una instancia
#
layer = MyDenseLayer(10)

#
# Propaga una señal a traves de la capa
#
layer(tf.zeros([8, 5]))

<tf.Tensor: shape=(8, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
#
# Solo despues de propagar la señal es posible
# ver las variables entrenables. Note que no hay un
# bias como en la capa tipo Dense
#
layer.trainable_variables

[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.0084079 , -0.00676134,  0.05705506,  0.02977188, -0.05499327,
         -0.04683509,  0.0156506 , -0.04320162, -0.09760814,  0.01561558],
        [ 0.10695203,  0.04114252, -0.09981413,  0.07230553, -0.03346606,
         -0.02394705,  0.08957603,  0.09043003,  0.0404571 ,  0.04284272],
        [-0.1083472 , -0.06586403,  0.0203122 ,  0.05173755, -0.05926293,
         -0.03395417, -0.02020734, -0.05852811,  0.07869694, -0.06526261],
        [-0.04351338, -0.04544047, -0.03308044,  0.10686912,  0.00191874,
          0.03189396,  0.02990426, -0.07682384, -0.00978146,  0.00207178],
        [ 0.0191799 ,  0.01270592,  0.03466138, -0.04077598,  0.01266582,
         -0.04604196, -0.01599293,  0.11362424,  0.02821803,  0.0156103 ]],
       dtype=float32)>]

In [8]:
#
# Continua siendo posible accesar a las variables
# de la capa por su nombre
#
layer.kernel

<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.0084079 , -0.00676134,  0.05705506,  0.02977188, -0.05499327,
        -0.04683509,  0.0156506 , -0.04320162, -0.09760814,  0.01561558],
       [ 0.10695203,  0.04114252, -0.09981413,  0.07230553, -0.03346606,
        -0.02394705,  0.08957603,  0.09043003,  0.0404571 ,  0.04284272],
       [-0.1083472 , -0.06586403,  0.0203122 ,  0.05173755, -0.05926293,
        -0.03395417, -0.02020734, -0.05852811,  0.07869694, -0.06526261],
       [-0.04351338, -0.04544047, -0.03308044,  0.10686912,  0.00191874,
         0.03189396,  0.02990426, -0.07682384, -0.00978146,  0.00207178],
       [ 0.0191799 ,  0.01270592,  0.03466138, -0.04077598,  0.01266582,
        -0.04604196, -0.01599293,  0.11362424,  0.02821803,  0.0156103 ]],
      dtype=float32)>

## Parámetros entrenables y no entrenables

In [9]:
class ComputeSum(tf.keras.layers.Layer):

    def __init__(self, input_dim):
        super(ComputeSum, self).__init__()
        self.total = tf.Variable(initial_value=tf.zeros((input_dim,)), trainable=False,)

    def call(self, inputs):
        self.total.assign_add(tf.reduce_sum(inputs, axis=0))
        return self.total


my_sum = ComputeSum(2)
x = tf.ones((2, 2))
x.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [10]:
my_sum(x).numpy()

array([2., 2.], dtype=float32)

In [11]:
my_sum(x).numpy()

array([4., 4.], dtype=float32)

In [12]:
my_sum.weights, my_sum.total

([<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([4., 4.], dtype=float32)>],
 <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([4., 4.], dtype=float32)>)

In [13]:
my_sum.non_trainable_weights, my_sum.total

([<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([4., 4.], dtype=float32)>],
 <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([4., 4.], dtype=float32)>)

In [14]:
my_sum.trainable_weights

[]

## Capas con capas

In [15]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32):
        super(Linear, self).__init__()
        self.units = units

    def build(self, input_shape):
        self.w = self.add_weight(
            shape=(input_shape[-1], self.units),
            initializer="random_normal",
            trainable=True,
        )
        self.b = self.add_weight(
            shape=(self.units,),
            initializer="random_normal",
            trainable=True,
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b


class MLP(tf.keras.layers.Layer):
    def __init__(self):
        super(MLP, self).__init__()
        self.linear_1 = Linear(32)
        self.linear_2 = Linear(32)
        self.linear_3 = Linear(10)

    def call(self, inputs):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.linear_2(x)
        x = tf.nn.relu(x)
        return self.linear_3(x)


mlp = MLP()

y = mlp(tf.ones(shape=(3, 64)))

len(mlp.weights)

6

In [16]:
#
# El modelo anterior es equivalente a:
#
mlp = tf.keras.Sequential(
    [
        keras.layers.Dense(32, activation=tf.nn.relu),
        keras.layers.Dense(32, activation=tf.nn.relu),
        keras.layers.Dense(10),
    ]
)

## Modo de enetrenamiento y modo de inferencia

In [17]:
class Dropout(keras.layers.Layer):
    def __init__(self, rate):
        super(Dropout, self).__init__()
        self.rate = rate

    def call(self, inputs, training=None):
        if training:
            return tf.nn.dropout(inputs, rate=self.rate)
        return inputs


class MLPWithDropout(keras.layers.Layer):
    def __init__(self):
        super(MLPWithDropout, self).__init__()
        self.linear_1 = Linear(32)
        self.dropout = Dropout(0.5)
        self.linear_3 = Linear(10)

    def call(self, inputs, training=None):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.dropout(x, training=training)
        return self.linear_3(x)


mlp = MLPWithDropout()
y_train = mlp(tf.ones((2, 2)), training=True)
y_test = mlp(tf.ones((2, 2)), training=False)

## Capas compuestas

In [18]:
#
# Se deriva de la clase Model cuando se requiere fit, evaluate, save, ...
#
class ResnetIdentityBlock(tf.keras.Model):
    
    def __init__(self, kernel_size, filters):
        #
        # Llama al constructor de la clase base
        # 
        super(ResnetIdentityBlock, self).__init__(name="")
        
        #
        # Parametros recibidos a traves del constructor
        #
        filters1, filters2, filters3 = filters

        #
        # Crea el modelo como una secuencia de capas
        #
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding="same")
        self.bn2b = tf.keras.layers.BatchNormalization()
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()

    def call(self, input_tensor, training=False):
        #
        # Propaga la señal de entrada cuando se recibe 
        # un input_tensor como entrada al modelo. La 
        # señal se propaga de una capa a otra mediante
        # la variable x
        #
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)
        
        #
        # Note que este modelo no es secuencial
        #
        x += input_tensor
        return tf.nn.relu(x)


#
# Ejemplo de la propagación de una señal
#
block = ResnetIdentityBlock(1, [1, 2, 3])
block(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [19]:
#
# Capas
#
block.layers

In [20]:
#
# Número de variables
#
len(block.variables)

18

In [21]:
#
# Resumen del modelo
#
block.summary()

Model: "resnet_identity_block"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              multiple                  4         
_________________________________________________________________
batch_normalization (BatchNo multiple                  4         
_________________________________________________________________
conv2d_1 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_1 (Batch multiple                  8         
_________________________________________________________________
conv2d_2 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_2 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
________________________________________________

In [22]:
len(block.variables)

18

In [23]:
block.summary()

Model: "resnet_identity_block"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              multiple                  4         
_________________________________________________________________
batch_normalization (BatchNo multiple                  4         
_________________________________________________________________
conv2d_1 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_1 (Batch multiple                  8         
_________________________________________________________________
conv2d_2 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_2 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
________________________________________________

## Creación de modelos con capas secuenciales

In [24]:
#
# Cuando el modelo es secuencial, se puede crear
# directamente a traves de Sequential
#
my_seq = tf.keras.Sequential(
    [
        tf.keras.layers.Conv2D(1, (1, 1), input_shape=(None, None, 3)),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Conv2D(2, 1, padding="same"),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Conv2D(3, (1, 1)),
        tf.keras.layers.BatchNormalization(),
    ]
)


my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [25]:
my_seq.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, None, None, 1)     4         
_________________________________________________________________
batch_normalization_3 (Batch (None, None, None, 1)     4         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, None, None, 2)     4         
_________________________________________________________________
batch_normalization_4 (Batch (None, None, None, 2)     8         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, None, None, 3)     9         
_________________________________________________________________
batch_normalization_5 (Batch (None, None, None, 3)     12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
_________________________________________________________