# Introducción básica para principiantes

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10),
    ]
)

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.04711078, -0.31855887,  0.6764848 ,  0.5596447 ,  0.11928979,
         0.01220848,  0.8269101 ,  0.3409326 ,  0.05164193,  0.05929246]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07149279, 0.05449716, 0.14740624, 0.13115138, 0.08443629,
        0.07586201, 0.17133446, 0.10538708, 0.07891327, 0.07951931]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.5788393

In [8]:
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4811 - accuracy: 0.8597
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1496 - accuracy: 0.9546
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1080 - accuracy: 0.9685
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0821 - accuracy: 0.9742
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0725 - accuracy: 0.9768


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0736 - accuracy: 0.9768


[0.07358972728252411, 0.9768000245094299]

In [11]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.01144032e-09, 1.05875140e-08, 2.01496960e-06, 2.11091101e-04,
        1.21248584e-11, 1.14470744e-07, 3.17006350e-14, 9.99786198e-01,
        2.91890476e-08, 5.20255583e-07],
       [4.52461579e-09, 1.87257756e-04, 9.99800265e-01, 1.18194548e-05,
        2.74464731e-17, 7.04371587e-07, 2.63967461e-08, 3.07545906e-14,
        2.53447201e-08, 3.11130639e-15],
       [5.43329293e-07, 9.98939335e-01, 1.31868277e-04, 1.28227866e-05,
        2.73440364e-05, 5.59935006e-06, 5.18590105e-06, 8.18699773e-04,
        5.85279704e-05, 1.05038993e-07],
       [9.99881029e-01, 2.61543875e-09, 6.51876471e-05, 4.62397111e-06,
        1.28147292e-07, 1.72743894e-05, 5.34567425e-06, 1.86129262e-06,
        2.23244257e-07, 2.43765735e-05],
       [1.82653650e-06, 1.13975126e-07, 4.19508297e-06, 2.60799624e-07,
        9.96836901e-01, 5.44951071e-08, 2.94827828e-06, 1.29267564e-05,
        6.67753284e-07, 3.14022996e-03]], dtype=float32)>