Eager Execution
===

* *60 min* | Última modificación: Julio 12, 2019.

## Preparación

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.enable_eager_execution()

## Cómputos con constantes en TensorFlow

In [3]:
##
##
#
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [4]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


## NumPy

In [9]:
ndarray = np.ones([3, 3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
tensor = tf.multiply(ndarray, 42)
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [7]:
print(np.add(tensor, 1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [8]:
##
## Tensor --> NumPy
##
print(tensor.numpy())

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


## GPU

In [10]:
print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
False
Is the Tensor on GPU #0:  
False
