Capa GaussianNoise --- 0:00 min
===

* Última modificación: Marzo 7, 2022 | YouTube

* Adaptado de: https://keras.io/api/layers/regularization_layers/gaussian_noise/

Suma ruido gaussiano centrado en cero. Esta técnica es util para mitigar el sobre-ajuste, ya que equivale a un aumento de datos aleaatorio. Funciona como si la entrada fuese un proceso corrupto.

Importación de librerías
---

In [1]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

tf.__version__

'2.8.0'

Ejemplos de uso
---

In [2]:
import numpy as np

layer = tf.keras.layers.GaussianNoise(
    stddev=0.2,
    seed=12345,
    input_shape=(2,),
)
data = np.arange(10).reshape(5, 2).astype(np.float32)
data

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [3]:
layer(
    data,
    training=True,
)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.17684934, 1.015686  ],
       [2.0272799 , 2.8778086 ],
       [4.3705134 , 4.769865  ],
       [5.8765774 , 6.7445674 ],
       [8.396073  , 9.275732  ]], dtype=float32)>

In [4]:
layer(
    data,
    training=True,
)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.10960626, 1.167422  ],
       [2.1752663 , 3.0928245 ],
       [4.075233  , 4.98608   ],
       [5.7705874 , 6.81417   ],
       [7.8808827 , 9.3056965 ]], dtype=float32)>