Detección de outliers usando EllipticEnvelope
===

* 0:00 min | Última modificación: Septiembre 22, 2021 | [YouTube]

En esta lección se aborda el problema de la detección de outliers en la muestra de entrenamiento suponiendo que los datos provienen de una distribución normal multivarida.

Esta metodología se basa en la computación de la probabilidad de ocurrencia (o la lejanía de un punto respecto al centro de los datos) si los datos siguen una disttribución normal multivariada. Ya que de antemano se supone la presencia de outliers, el vector de centros  y la matriz de covarianzas se deben estimar usando métodos robustos (es decir, que no sean influenciados por las observaciones atípicas).

En esta metodología se usa la distancia de Mahalanobis para derivar una medida que indica que tan lejano es un punto.

![ellipsoide.png](assets/ellipsoide.png)

In [1]:
import numpy as np
from sklearn.covariance import EllipticEnvelope

true_cov = np.array(
    [
        [0.8, 0.3],
        [0.3, 0.4],
    ]
)


X = np.random.RandomState(0).multivariate_normal(
    mean=[0, 0],
    cov=true_cov,
    size=500,
)

cov = EllipticEnvelope(
    # -----------------------------------------------------
    # The data is centered?
    assume_centered=False,
    # -----------------------------------------------------
    # The amount of contamination of the data set
    contamination=0.1,
    # -----------------------------------------------------
    # The proportion of points to be included in the
    # support of the raw MCD estimate.
    support_fraction=None,
    # -----------------------------------------------------
    # Determines the pseudo random number generator for
    # shuffling the data.
    random_state=0,
)

cov.fit(X)

#
# El objeto entrenado contiene los siguientes atributos:
#   location_
#   covariance_
#   support_
#


#
# Un valor de +1 indica que el punto es un inlier
# y un -1 indica que es un outlier
#
cov.predict([[0, 0], [3, 3]])

array([ 1, -1])

In [2]:
cov.covariance_

array([[0.74118335, 0.25357049],
       [0.25357049, 0.30531502]])

In [3]:
cov.location_

array([0.0813539 , 0.04279722])